-- MySQL Script generated by MySQL Workbench
-- Mon Sep 21 19:30:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pakchoi_pos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pakchoi_pos` ;

-- -----------------------------------------------------
-- Schema pakchoi_pos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pakchoi_pos` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pakchoi_pos` ;

-- -----------------------------------------------------
-- Table `vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vendor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL COMMENT '供应商公司名称',
  `tel` VARCHAR(32) NULL,
  `url` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `add_time` DATETIME NOT NULL,
  `operator` INT NOT NULL,
  `status` INT NULL,
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '供应商信息';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `vendor` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `realname` VARCHAR(16) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `addtime` DATETIME NOT NULL,
  `avatar` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `admin` (`id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `realname_UNIQUE` ON `admin` (`realname` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `admin` (`email` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goods` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '商品名称',
  `add_time` DATETIME NOT NULL COMMENT '添加时间',
  `price` DOUBLE NOT NULL COMMENT '单价',
  `gender` INT NOT NULL COMMENT '男装或者女装',
  `display` LONGTEXT NOT NULL COMMENT '显示图片的datauri base64字符串',
  `item_id` VARCHAR(255) NOT NULL COMMENT '供应商的内部编号',
  `vendor_id` INT NOT NULL,
  `operator` INT NOT NULL,
  `note` MEDIUMTEXT NULL COMMENT '对商品的简要描述信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `goods` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `inventories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `inventories` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '与库存流水记录相关联的编号',
  `batch_id` VARCHAR(45) NOT NULL COMMENT '库存批次号(人类可读的文本编码)',
  `inbound_time` DATETIME NOT NULL COMMENT '入库时间',
  `item_id` INT NOT NULL COMMENT '商品号',
  `count` INT NOT NULL COMMENT '入库的数量',
  `note` MEDIUMTEXT NULL,
  `operator` INT NOT NULL,
  PRIMARY KEY (`id`, `batch_id`))
ENGINE = InnoDB
COMMENT = '货物批次库存';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `inventories` (`id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `batch_id_UNIQUE` ON `inventories` (`batch_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `VIP_members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VIP_members` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `VIP_members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `gender` INT NOT NULL,
  `phone` VARCHAR(32) NULL,
  `address` VARCHAR(64) NULL,
  `join_time` DATETIME NOT NULL,
  `operator` INT NOT NULL,
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `VIP_members` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `waterflow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `waterflow` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `waterflow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `goods` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `count` INT NOT NULL COMMENT '售卖的数量或者入库的数量',
  `money` DOUBLE NOT NULL COMMENT '售卖的总价或者入库的总价',
  `batch_id` INT NOT NULL COMMENT '库存的批次号',
  `buyer` INT NOT NULL COMMENT '0: anonymous\n-1: me\n> 1: VIP members',
  `operator` INT NOT NULL,
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `waterflow` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `role` (`id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
