-- MySQL Script generated by MySQL Workbench
-- Thu Sep 10 22:45:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vendor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '供应商公司名称',
  `tel` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '供应商信息';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `vendor` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goods` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '商品名称',
  `add_time` DATETIME NOT NULL COMMENT '添加时间',
  `price` DOUBLE NOT NULL COMMENT '单价',
  `gender` INT NOT NULL COMMENT '男装或者女装',
  `display` LONGTEXT NOT NULL COMMENT '显示图片的datauri base64字符串',
  `info` VARCHAR(45) NULL COMMENT '对商品的简要描述信息',
  `vendor_item_id` VARCHAR(45) NOT NULL COMMENT '供应商的内部编号',
  `vendor_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `goods` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `inventories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `inventories` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '与库存流水记录相关联的编号',
  `batch_id` VARCHAR(45) NOT NULL COMMENT '库存批次号(人类可读的文本编码)',
  `inbound_time` DATETIME NOT NULL COMMENT '入库时间',
  `item_id` INT NOT NULL COMMENT '商品号',
  `count` INT NOT NULL COMMENT '入库的数量',
  PRIMARY KEY (`id`, `batch_id`))
ENGINE = InnoDB
COMMENT = '货物批次库存';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `inventories` (`id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `batch_id_UNIQUE` ON `inventories` (`batch_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `waterflow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `waterflow` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `waterflow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `goods` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `count` INT NOT NULL COMMENT '售卖的数量或者入库的数量',
  `money` DOUBLE NOT NULL COMMENT '售卖的总价或者入库的总价',
  `batch_id` INT NOT NULL COMMENT '库存的批次号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `waterflow` (`id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
