-- MySQL Script generated by MySQL Workbench
-- Wed Sep  9 20:05:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goods` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `add_time` DATETIME NOT NULL,
  `price` DOUBLE NOT NULL,
  `gender` INT NOT NULL COMMENT '男装或者女装',
  `display` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `goods` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `waterflow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `waterflow` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `waterflow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `goods` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `count` INT NOT NULL,
  `money` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `waterflow` (`id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
