.\" man page create by R# package system.
.TH RDF_TOOLS 1 2000-Jan "get_cid_tupleData" "get_cid_tupleData"
.SH NAME
get_cid_tupleData \- 
.SH SYNOPSIS
\fIget_cid_tupleData(\fBfile\fR as any, 
\fBlazy\fR as boolean = FALSE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
rdf_tools
.SH FILES
.PP
pubchem.dll
.PP
